version: '3'

services:
  nginx:
    image: nginx:latest
    expose:
      - 80
    ports:
      - "80:80"
    volumes:
      - ./config_nginx:/etc/nginx/conf.d
    depends_on:
      - web
  db:
    image: postgres
  web:
    image: ${IMAGE}
    depends_on:
        - db
        - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
