version: '3'

services:
  nginx:
    image: nginx:1.14
    expose:
      - 80
    ports:
      - "80:80"
    volumes:
      - /home/ec2-user/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
  db:
    image: postgres:9.6
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
  web:
    image: ${IMAGE}
    ports:
        - "8000:8000"
    depends_on:
        - db
        - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
