version: '3'

services:
  nginx:
    image: nginx:latest
    expose:
      - 80
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./config_nginx:/etc/nginx/conf.d
    depends_on:
      - web
  db:
    image: postgres
  elasticsearch:
    image: "elasticsearch:2.4.1"
    ports:
    - "9200:9200"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
    - db
    - elasticsearch
    entrypoint: ./docker-entrypoint.sh
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A library worker -B -l info
    volumes:
    - .:/app
    depends_on:
    - web
    - redis


