version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py migrate --noinput
    command: ./load_db.sh
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_DEBUG = False
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A library worker -B -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
