version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config_files/nginx.conf:/etc/nginx/conf.d/
    depends_on:
      - web
  db:
    image: postgres
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - .:/app
    depends_on:
    - db
    - redis
    entrypoint: ./docker-entrypoint.sh
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A library worker -B -l info
    volumes:
    - .:/app
    depends_on:
    - web
    - redis


