version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: bash -c "python manage.py migrate && ./load_db.sh && python manage.py runserver 0.0.0.0:8000"
    container_name: web_library
    volumes:
    - .:/code
    ports:
    - "8000:8000"
    depends_on:
    - db
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A library worker -B -l info
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
