# Generated by Django 2.1.1 on 2018-09-19 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylib.Author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylib.Book')),
            ],
        ),
    ]
