# Generated by Django 2.1.1 on 2018-10-15 11:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mylib.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mylib', '0007_auto_20180927_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='author_photo/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_cover/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='number_page',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(validators=[mylib.validators.validate_year]),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publishing_house',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='publishing', to='mylib.PublishingHouse'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists'}, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_subscription',
            field=models.BooleanField(default=False, verbose_name='send email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
